### ISSUE TITLE
refactor : done and todo

### ISSUE THREAD

**Issue by tmos** [sebsauvage/MinigalNano#114]
Hi everyone

I'm currently doing a big refactor on MiniGal. It need like _a lot_ of cleaning, and now is the time. Some changes will probably bother more than one people, but it will definitely allow MiniGal to be more accessible and, moreover, much more modern, in a code point of view. 

Don't worry, KISS is still here, nothing changes more than the dirty old code !

So don't except new features with the refactor itself. But this refactor will allow new features to be done much easier and faster. #44, #32, #111, #112, #113 are in my mind ! I plan to beat down every issue after the refactor 💪 .

So, here is what I'm doing, and what is still to be done. I don't expect any help, I'm really close to the end, but if you see anything worth discussion, don't hesitate :)
# General direction
- [X] index.php just return raw data to the template, no processed HTML. More freedom for the templaters, and more flexibility.
- [X] clean all the code, remove undeclared variables, uniformisation of the style, php linting, etc.
- [X] Make templates more independent, allowing them to have their own dependencies, so everyone is able to craft his own theme (with, without lightbox, jquery, bootstrap, etc.).
# Theme
- [X] Switch from HTML with fake templating system `<% ... %>` to PHP native inline templating abilities `<?php if (...) : ?>` `<?php foreach (... as ...) : ?>`.
- [X] Adapt the templates to the new returned data from index.php
# Board default theme
- [X] Modern frontend workflow (gulp, linting, less, etc.)
- [X] Let's go to 2016 modern standards, and drop some old browsers (flexbox, vh, etc.)
- [X] Modern libraries (custom fontawesome, bootstrap grid (just the grid, not everything), jquery 3).
- [X] Full CSS & JS minification
- [ ] Better SEO (meta description, alt, unique content, etc.)

For information, the default Board theme will become a little bit more complex to edit (due to gulp and less), but this will be much more efficient in a coding point of view, and cleaner. So to allow people to keep their old customizations, a Board-legacy theme will be shipped, with minimal modifications from the 0.4 and instructions to keep your modifications online :)

So you may ask : what still need to be done ?
Actually, just the regular gravels in MinigalNano's shoe :
- [ ] Lightbox (I'll finally do this myself, no lib, old school)

And We will be ok for the .5 of minigal !

And plans for the future : 
- [ ] Proprotional pictures cropping
- [ ] Proper translating system (csv, po, ... ?)
- [ ] Better comments system, allowing to add more data to the pictures (title, desc, link, alt, title, etc.) through a CSV-like file. But nothing planned yet.

All of this is already online in the `refactor` branch, don't hesistate to have a look :)

**Comment by MaraKat** [comment]
Hello  !
And thank you for your commit.
What is the use of the node modules ? Are they only as help to make templates ? What will happen if I do not upload them ? Are some of them absolutely necessary ?

**Comment by tmos** [comment]
They are here just for the developpement, no need to be uploaded for production if I remember well :)
